import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { codeAgent } from './code-agent';

describe('CodeAgent', () => {
  let repoDir: string;
  let previousRepoRoot: string | undefined;

  beforeEach(() => {
    repoDir = fs.mkdtempSync(path.join(os.tmpdir(), 'orbit-code-agent-'));
    fs.mkdirSync(path.join(repoDir, 'backend', 'src'), { recursive: true });
    previousRepoRoot = process.env.ORBIT_REPO_ROOT;
    process.env.ORBIT_REPO_ROOT = repoDir;
  });

  afterEach(() => {
    if (previousRepoRoot === undefined) {
      delete process.env.ORBIT_REPO_ROOT;
    } else {
      process.env.ORBIT_REPO_ROOT = previousRepoRoot;
    }

    fs.rmSync(repoDir, { recursive: true, force: true });
  });

  it('writes real generated module files into the repo workspace', async () => {
    const execution = await codeAgent.execute({
      action: 'generate',
      feature: 'Phase 3 Demo',
      description: 'Generated by a real code agent'
    });

    expect(execution.status).toBe('completed');
    expect(execution.output?.generated).toBe(true);
    expect(execution.output?.files).toHaveLength(3);

    const generatedDir = path.join(repoDir, 'backend', 'src', 'generated', 'phase-3-demo');
    expect(fs.existsSync(path.join(generatedDir, 'index.ts'))).toBe(true);
    expect(fs.existsSync(path.join(generatedDir, 'utils.ts'))).toBe(true);
    expect(fs.existsSync(path.join(generatedDir, 'config.ts'))).toBe(true);
  });

  it('modifies an existing generated file for the feature', async () => {
    await codeAgent.execute({
      action: 'generate',
      feature: 'Phase 3 Demo'
    });

    const execution = await codeAgent.execute({
      action: 'modify',
      feature: 'Phase 3 Demo',
      description: 'phase-3-update'
    });

    expect(execution.status).toBe('completed');
    const filePath = path.join(repoDir, 'backend', 'src', 'generated', 'phase-3-demo', 'index.ts');
    const content = fs.readFileSync(filePath, 'utf8');
    expect(content).toContain('phase-3-update');
  });
});
